---
- name: check for short-circuit
  raw: "> /dev/null command -v mysql;"
  register: installed
  ignore_errors: True
  changed_when: False

- name: set should_run fact
  set_fact:
    should_run: "{{installed|failed or not mysql_should_shortcircuit}}"

- include: compat.yml

- include: include_vars.yml

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: install_package_names.yml

- name: start mysql
  service: name={{service_name}} state=started
  sudo: yes
  when: >
    not (is_integration_test is defined and is_integration_test and
    ansible_os_family == "RedHat")
